config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "application#welcome"
  get "chat_room/", to: "application#chat"
  scope "/:locale" do
    devise_for :students, path: "students", controllers: {sessions: "students/sessions",
                                                          registrations: "students/registrations",
                                                          passwords: "students/passwords"}
    devise_for :teachers, path: "teachers", controllers: {sessions: "teachers/sessions",
                                                          registrations: "teachers/registrations",
                                                          passwords: "students/passwords"}

    resources :subject_teachers
    resources :groups do
      member do
        get "add_students", action: "add_students_form"
        get "remove_students", action: "remove_students_form"
      end
      post "set_captain", on: :member
      post "add_students", on: :member
      post "remove_students", on: :member
    end
    resources :teachers
    resources :subjects do
      member do
        get "add_group", action: "add_group_form"
      end
      collection do
        get "export_csv"
      end
      post "add_group", on: :member
    end
    resources :lessons
    resources :tasks
    resources :students
    resources :marks
    resources :student_responses do
      post "evaluate", on: :member
    end
  end

  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["id", "email", "created_at", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :students, join_table: "groups_students"
  has_and_belongs_to_many :subjects
  has_many :group_students

  def captain
    captain_relation = group_students.find_by(captain: true)
    return unless captain_relation

    Student.find(captain_relation.student_id)
  end
end

app/models/group_student.rb
class GroupStudent < ApplicationRecord
  self.table_name = "groups_students"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :tasks
  enum lesson_type: {lecture: 0, seminar: 1, practical: 2}
  enum lesson_time: {
    "8:30" => 0,
    "10:10" => 1,
    "12:00" => 2,
    "13:40" => 3,
    "15:20" => 4,
    "17:00" => 5
  }

  scope :week_lessons, LessonsWeek
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  belongs_to :task

  validates :mark, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :recipient, polymorphic: true
end

app/models/student.rb
class Student < ApplicationRecord
  VALID_CURRENCIES = %w[USD EUR UAH].freeze
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :currency, presence: true, inclusion: { in: VALID_CURRENCIES }

  has_and_belongs_to_many :groups
  has_many :student_responses
  has_many :messages, as: :recipient
  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def currency_rates
    CurrencyRateService.call(self)
  end
end

app/models/student_response.rb
class StudentResponse < ApplicationRecord
  belongs_to :student
  belongs_to :task

  has_one_attached :file
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :teacher
  has_many :lessons

  scope :my_subjects, StudentSubjects

  def self.ransackable_attributes(auth_object = nil)
    %w[id title description hours created_at updated_at difficulty_level teacher_id lessons_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[groups lessons teacher]
  end

  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def self.to_csv
    attributes = %w{id title description hours created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << attributes.map { |attr| item.send(attr) }
      end
    end
  end

end

app/models/subject_teacher.rb
class SubjectTeacher < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :lesson
  has_many :student_responses, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  VALID_CURRENCIES = %w[USD EUR UAH].freeze
  validate :valid_email_domain

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :currency, presence: true, inclusion: { in: VALID_CURRENCIES }


  has_many :subjects
  has_many :messages, as: :recipient
  def first_initials
    "#{last_name} #{first_name.first}. #{middle_name.first}."
  end
  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def currency_rates
    CurrencyRateService.call(self)
  end

  private

  def valid_email_domain
    allowed_domains = ["karazin.ua"]
    email_domain = email.split("@").last if email.present?
    return if allowed_domains.include?(email_domain)

    errors.add(:email, "wrong domen")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @student_responses = @task.student_responses
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.lesson = Lesson.find_by(id: task_params[:lesson_id])
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :lesson_id, :notes, :deadline, :material, :max_mark)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <%= form.hidden_field :lesson_id, value: params[:lesson_id] %>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :deadline, style: "display: block" %>
    <%= form.date_field :deadline %>
  </div>

  <div>
    <%= form.label :material, style: "display: block" %>
    <%= form.text_area :material %>
  </div>

  <div>
    <%= form.label :max_mark, style: "display: block" %>
    <%= form.number_field :max_mark %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Lesson:</strong>
    <%= task.lesson_id %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= task.notes %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= task.deadline %>
  </p>

  <p>
    <strong>Material:</strong>
    <%= task.material %>
  </p>

  <p>
    <strong>Max mark:</strong>
    <%= task.max_mark %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <% if teacher_signed_in? %>
    <% if @student_responses.any? %>
      <h2>Student Responses:</h2>
      <ul>
        <% @student_responses.each do |response| %>
          <li>
            <%= link_to response.student.full_name, student_response_path(response) %>
            <% if response.mark_id.present? %>
              <% mark = Mark.find(response.mark_id) %>
              <span style="color: green;"><%= mark.mark %></span>
            <% else %>
              <span style="color: red;"> Not evaluated </span>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No responses yet.</p>
    <% end %>
    <%= link_to "Edit this task", edit_task_path(@task), class: "btn btn-primary m-2 rounded" %> |
    <%= button_to "Destroy this task", @task, method: :delete, class: "btn btn-primary m-2 rounded" %>
  <% end %>

  <%= link_to "Back to lesson", lesson_path(@task.lesson), class: "btn btn-primary m-2 rounded" %>

  <% if student_signed_in? %>
    <% if current_student.student_responses.exists?(task_id: @task.id) %>
      <% response = current_student.student_responses.find_by(task_id: @task.id) %>
      <% if response.mark_id.present? %>
        <p>Your response has been evaluated. Mark: <%= Mark.find(response.mark_id).mark %></p>
      <% else %>
        <p>Your response has not been evaluated yet.</p>
      <% end %>
      <%= link_to "View your response", student_response_path(response), class: "btn btn-primary m-2 rounded" %>
    <% else %>
      <%= link_to "Provide your answer", new_student_response_path(task_id: @task.id), class: "btn btn-primary m-2 rounded" %>
    <% end %>
  <% end %>
</div>