config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "application#welcome"
  get "chat_room/", to: "application#chat"
  scope "/:locale" do
    devise_for :students, path: "students", controllers: {sessions: "students/sessions",
                                                          registrations: "students/registrations",
                                                          passwords: "students/passwords"}
    devise_for :teachers, path: "teachers", controllers: {sessions: "teachers/sessions",
                                                          registrations: "teachers/registrations",
                                                          passwords: "students/passwords"}

    resources :subject_teachers
    resources :groups do
      member do
        get "add_students", action: "add_students_form"
        get "remove_students", action: "remove_students_form"
      end
      post "set_captain", on: :member
      post "add_students", on: :member
      post "remove_students", on: :member
    end
    resources :teachers
    resources :subjects do
      member do
        get "add_group", action: "add_group_form"
      end
      collection do
        get "export_csv"
      end
      post "add_group", on: :member
    end
    resources :lessons
    resources :tasks
    resources :students
    resources :marks
    resources :student_responses do
      post "evaluate", on: :member
    end
  end

  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["id", "email", "created_at", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :students, join_table: "groups_students"
  has_and_belongs_to_many :subjects
  has_many :group_students

  def captain
    captain_relation = group_students.find_by(captain: true)
    return unless captain_relation

    Student.find(captain_relation.student_id)
  end
end

app/models/group_student.rb
class GroupStudent < ApplicationRecord
  self.table_name = "groups_students"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :tasks
  enum lesson_type: {lecture: 0, seminar: 1, practical: 2}
  enum lesson_time: {
    "8:30" => 0,
    "10:10" => 1,
    "12:00" => 2,
    "13:40" => 3,
    "15:20" => 4,
    "17:00" => 5
  }

  scope :week_lessons, LessonsWeek
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  belongs_to :task

  validates :mark, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :recipient, polymorphic: true
end

app/models/student.rb
class Student < ApplicationRecord
  VALID_CURRENCIES = %w[USD EUR UAH].freeze
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :currency, presence: true, inclusion: { in: VALID_CURRENCIES }

  has_and_belongs_to_many :groups
  has_many :student_responses
  has_many :messages, as: :recipient
  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def currency_rates
    CurrencyRateService.call(self)
  end
end

app/models/student_response.rb
class StudentResponse < ApplicationRecord
  belongs_to :student
  belongs_to :task

  has_one_attached :file
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :teacher
  has_many :lessons

  scope :my_subjects, StudentSubjects

  def self.ransackable_attributes(auth_object = nil)
    %w[id title description hours created_at updated_at difficulty_level teacher_id lessons_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[groups lessons teacher]
  end

  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def self.to_csv
    attributes = %w{id title description hours created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << attributes.map { |attr| item.send(attr) }
      end
    end
  end

end

app/models/subject_teacher.rb
class SubjectTeacher < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :lesson
  has_many :student_responses, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  VALID_CURRENCIES = %w[USD EUR UAH].freeze
  validate :valid_email_domain

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :currency, presence: true, inclusion: { in: VALID_CURRENCIES }


  has_many :subjects
  has_many :messages, as: :recipient
  def first_initials
    "#{last_name} #{first_name.first}. #{middle_name.first}."
  end
  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def currency_rates
    CurrencyRateService.call(self)
  end

  private

  def valid_email_domain
    allowed_domains = ["karazin.ua"]
    email_domain = email.split("@").last if email.present?
    return if allowed_domains.include?(email_domain)

    errors.add(:email, "wrong domen")
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_students
    @group = Group.find(params[:id])
    student_ids = params[:group][:student_ids]
    AddStudentsToGroupService.new(@group, student_ids).call
    redirect_to @group, notice: "Students were successfully added to the group."
  end

  def add_students_form
    @group = Group.find(params[:id])
  end

  def remove_students_form
    @group = Group.find(params[:id])
  end

  def remove_students
    @group = Group.find(params[:id])
    student_ids = params[:group][:student_ids]
    if student_ids.present?
      students = Student.where(id: student_ids)
      @group.students.delete(students)
      redirect_to @group, notice: "Students were successfully removed from the group."
    else
      redirect_to @group, alert: "Please select students to remove."
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_captain
    @group = Group.find(params[:id])
    notice_message = SetGroupCaptainService.new(@group, params[:group][:captain_id]).call
    redirect_to @group, notice: notice_message
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label"  %>
    <%= form.text_area :name, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<p>
  <strong class="card-text"><%= t('name') %>:</strong>
  <%= group.name %>
</p>
<p>
  <strong class="card-text"><%= t('students_count') %>:</strong>
  <%= group.students.count %>
</p>

app/views/groups/add_students_form.html.erb
<div class="container mt-3">
  <p class="text-success"><%= notice %></p>

  <%= render @group %>

  <% if @group.students.any? %>
    <h2>Students:</h2>
    <ul>
      <% @group.students.each do |student| %>
        <li><%= student.first_name %>  <%= student.middle_name %> <%= student.last_name %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No students in this group.</p>
  <% end %>

  <% if teacher_signed_in? %>
    <%= form_with(model: @group, url: add_students_group_path(@group), method: :post, class: "student-form") do |f| %>
      <div class="row g-3">
        <div class="col-md-6">
          <%= text_field_tag :search, nil, placeholder: "Search students", class: "form-control", id: "searchInput" %>
        </div>
      </div>
      <div class="row g-3 mt-3">
        <div class="col-md-6">
          <%= f.label "Select students to add:" %>
          <div class="student-list" style="max-height: 200px; overflow-y: auto;">
            <% Student.where.not(id: @group.student_ids).each do |student| %>
              <div class="form-check">
                <%= check_box_tag "group[student_ids][]", student.id, @group.students.exclude?(student), class: "form-check-input" %>
                <%= label_tag "group_student_ids_#{student.id}", student.full_name, class: "form-check-label" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row g-3 mt-3">
        <div class="col-md-6">
          <%= f.submit "Add Students", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<script type="text/javascript" charset="utf-8">

    document.addEventListener('DOMContentLoaded', function() {
        const searchInput = document.querySelector('#searchInput');
        const studentList = document.querySelector('.student-list');
        searchInput.addEventListener('input', function() {
            const searchValue = this.value.toLowerCase();
            const students = studentList.querySelectorAll('.form-check-label');

            students.forEach(function(student) {
                const fullName = student.textContent.toLowerCase();
                if (fullName.includes(searchValue)) {
                    student.parentElement.style.display = 'block';
                } else {
                    student.parentElement.style.display = 'none';
                }
            });
        });
    });

</script>

app/views/groups/edit.html.erb
<div class="d-flex flex-column align-items-center">
  <h1>Editing group</h1>
  <% if teacher_signed_in? %>
    <%= render "form", group: @group %>
    <%= form_with(model: @group, url: set_captain_group_path(@group), method: :post, class: "captain-form") do |f| %>
      <div class="field">
        <%= f.label "Select captain:" %><br>
        <%= f.collection_select :captain_id, @group.students, :id, :full_name %>
      </div>
      <div class="actions">
        <%= f.submit "Set Captain" %>
      </div>
    <% end %>
  <% end %>
      <div>
        <%= link_to "Show this group", @group, class: "btn btn-primary m-2 rounded" %> |
        <%= link_to "Back to groups", groups_path, class: "btn btn-secondary m-2 rounded" %>
      </div>

</div>

app/views/groups/index.html.erb
<div class="d-flex flex-column align-items-center">
  <p style="color: green"><%= notice %></p>
  <h1><%= t("groups") %></h1>
  <div id="groups" class="row row-cols-1 row-cols-md-3 g-1">
    <% if current_student %>
      <% current_student.groups.each do |group| %>
        <div class="col mb-2">
          <div class="card" style="width: 18rem;" id="<%= dom_id group %>">
            <div class="card-body">
              <%= render group %>
              <p>
                <%= link_to "#{t("common.show")} #{t("group")}" , group, class: "btn btn-primary" %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <% @groups.each do |group| %>
        <div class="col mb-2">
          <div class="card" style="width: 18rem;" id="<%= dom_id group %>">
            <div class="card-body">
              <%= render group %>
              <p>
                <%= link_to "#{t("common.show")} #{t("group")}", group, class: "btn btn-primary" %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if teacher_signed_in? %>
    <%= link_to "#{t("common.new")} #{t("group")}", new_group_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="d-flex flex-column align-items-center">
  <p style="color: green"><%= notice %></p>

  <h1>New group</h1>

  <%= render "form", group: @group %>
  <%= link_to "Back to groups", groups_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/groups/remove_students_form.html.erb
<div class="container mt-3">
  <p class="text-success"><%= notice %></p>

  <%= render @group %>

  <% if @group.students.any? %>
    <h2>Students:</h2>
    <ul>
      <% @group.students.each do |student| %>
        <li><%= student.first_name %>  <%= student.middle_name %> <%= student.last_name %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No students in this group.</p>
  <% end %>

  <% if teacher_signed_in? %>
    <%= form_with(model: @group, url: remove_students_group_path(@group), method: :post, class: "student-form") do |f| %>
      <div class="row g-3">
        <div class="col-md-6">
          <%= text_field_tag :search, nil, placeholder: "Search students", class: "form-control", id: "searchInput" %>
        </div>
      </div>
      <div class="row g-3 mt-3">
        <div class="col-md-6">
          <%= f.label "Select students to remove:" %>
          <div class="student-list" style="max-height: 200px; overflow-y: auto;">
            <% @group.students.each do |student| %>
              <div class="form-check">
                <%= check_box_tag "group[student_ids][]", student.id, false, class: "form-check-input" %>
                <%= label_tag "group_student_ids_#{student.id}", student.full_name, class: "form-check-label" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row g-3 mt-3">
        <div class="col-md-6">
          <%= f.submit "Remove Students", class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<script type="text/javascript" charset="utf-8">

    document.addEventListener('DOMContentLoaded', function() {
        const searchInput = document.querySelector('#searchInput');
        const studentList = document.querySelector('.student-list');
        searchInput.addEventListener('input', function() {
            const searchValue = this.value.toLowerCase();
            const students = studentList.querySelectorAll('.form-check-label');

            students.forEach(function(student) {
                const fullName = student.textContent.toLowerCase();
                if (fullName.includes(searchValue)) {
                    student.parentElement.style.display = 'block';
                } else {
                    student.parentElement.style.display = 'none';
                }
            });
        });
    });

</script>

app/views/groups/show.html.erb
<div class="container mt-3">
  <p class="text-success"><%= notice %></p>

  <%= render @group %>

  <% if @group.students.any? %>
    <p>
      <strong class="card-text">Captain:</strong>
      <%= @group.captain ? @group.captain.full_name : "None" %>
    </p>
    <h2><%= t("students") %>:</h2>
    <ul>
      <% @group.students.each do |student| %>
        <li><%= student.first_name %>  <%= student.middle_name %> <%= student.last_name %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No students in this group.</p>
  <% end %>

  <% if teacher_signed_in? %>
    <div class="btn-group mt-2" role="group" aria-label="Group actions">
      <%= link_to t("common.edit"), edit_group_path(@group), class: "btn btn-primary m-2 rounded" %>
      <%= link_to "#{t('common.back')} #{t('common.to')} #{t("groups")}", groups_path, class: "btn btn-secondary m-2 rounded" %>
      <%= link_to "#{t('common.add')} #{t('student')}", add_students_group_path(@group), class: "btn btn-secondary m-2 rounded" %>
      <%= link_to "#{t('common.remove')} #{t('student')}", remove_students_group_path(@group), class: "btn btn-secondary m-2 rounded" %>
      <%= button_to t('common.destroy'), @group, method: :delete, class: "btn btn-danger m-2 rounded" %>
    </div>
  <% end %>

</div>