config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "application#welcome"
  get "chat_room/", to: "application#chat"
  scope "/:locale" do
    devise_for :students, path: "students", controllers: {sessions: "students/sessions",
                                                          registrations: "students/registrations",
                                                          passwords: "students/passwords"}
    devise_for :teachers, path: "teachers", controllers: {sessions: "teachers/sessions",
                                                          registrations: "teachers/registrations",
                                                          passwords: "students/passwords"}

    resources :subject_teachers
    resources :groups do
      member do
        get "add_students", action: "add_students_form"
        get "remove_students", action: "remove_students_form"
      end
      post "set_captain", on: :member
      post "add_students", on: :member
      post "remove_students", on: :member
    end
    resources :teachers
    resources :subjects do
      member do
        get "add_group", action: "add_group_form"
      end
      collection do
        get "export_csv"
      end
      post "add_group", on: :member
    end
    resources :lessons
    resources :tasks
    resources :students
    resources :marks
    resources :student_responses do
      post "evaluate", on: :member
    end
  end

  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :teacher
  has_many :lessons

  scope :my_subjects, StudentSubjects

  def self.ransackable_attributes(auth_object = nil)
    %w[id title description hours created_at updated_at difficulty_level teacher_id lessons_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[groups lessons teacher]
  end

  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def self.to_csv
    attributes = %w{id title description hours created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << attributes.map { |attr| item.send(attr) }
      end
    end
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.my_subjects(current_teacher: current_teacher, current_student: current_student)
  end

  # GET /subjects/1 or /subjects/1.json
  def show; end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit; end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)
    @subject.teacher = current_teacher

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def export_csv
    @subjects = Subject.my_subjects(current_teacher: current_teacher, current_student: current_student)

    respond_to do |format|
      format.csv { send_data @subjects.to_csv, filename: "subjects-#{Date.today}.csv" }
    end
  end

  def add_group
    @subject = Subject.find(params[:id])
    group_ids = params[:subject][:group_ids]
    if group_ids.present?
      groups = Group.where(id: group_ids).where.not(id: @subject.group_ids)
      @subject.groups << groups
      redirect_to @subject, notice: "Students were successfully added to the group."
    else
      redirect_to @subject, alert: "Please select students to add."
    end
  end

  def add_group_form
    @subject = Subject.find(params[:subject_id])
  end

  def remove_group_form
    @subject = Subject.find(params[:subject_id])
    @group = Group.find(params[:id])
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy!

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(:subject_id, :title, :description, :hours, :difficulty_level, :lessons_id)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label"  %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :hours, class: "form-label" %>
    <%= form.number_field :hours, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label"  %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<p>
  <strong class="card-text"><%= t("name") %>:</strong>
  <%= subject.title %>
</p>
<p>
  <strong class="card-text"><%= t("group") %>:</strong>
  <% subject.groups.each do |group| %>
    <%= group.name %><br>
  <% end %>
</p>
<p>
  <strong class="card-text"><%= t("teacher") %>:</strong>
  <%= subject.teacher.first_initials %>
</p>
<p>
  <strong class="card-text"><%= t("hours_count") %>:</strong>
  <%= subject.hours %>
</p>

app/views/subjects/add_group_form.html.erb
<div class="container mt-3">
  <p class="text-success"><%= notice %></p>

  <%= render @subject %>

  <% if @subject.groups.any? %>
    <h2>Groups:</h2>
    <ul>
      <% @subject.groups.each do |group| %>
        <li><%= group.name %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No groups for this subject.</p>
  <% end %>

  <% if teacher_signed_in? %>
    <%= form_with(model: [@subject, Group.new], url: add_group_subject_path(@subject), method: :post, class: "group-form") do |f| %>
      <div class="row g-3">
        <div class="col-md-6">
          <%= text_field_tag :search, nil, placeholder: "Search groups", class: "form-control search-input" %>
        </div>
      </div>
      <div class="row g-3 mt-3">
        <div class="col-md-6">
          <%= f.label "Select groups to add:" %>
          <div class="group-list" style="max-height: 200px; overflow-y: auto;">
            <% Group.where.not(id: @subject.group_ids).each do |group| %>
              <div class="form-check">
                <%= check_box_tag "subject[group_ids][]", group.id, @subject.groups.exclude?(group), class: "form-check-input" %>
                <%= label_tag "subject_group_ids_#{group.id}", group.name, class: "form-check-label" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row g-3 mt-3">
        <div class="col-md-6">
          <%= f.submit "Add Groups", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<div class="d-flex flex-column align-items-center">
  <h1>Editing subject</h1>

  <%= render "form", subject: @subject %>

  <div>
    <%= link_to "Show this subject", @subject, class: "btn btn-primary m-2 rounded" %> |
    <%= link_to "Back to subjects", subjects_path, class: "btn btn-secondary m-2 rounded" %>
  </div>
</div>

app/views/subjects/index.html.erb
<div class="d-flex flex-column align-items-center">
  <p style="color: green"><%= notice %></p>

  <h1><%= t("subjects") %></h1>

  <div id="subject" class="row row-cols-1 row-cols-md-3 g-1">
    <% @subjects.each do |subject| %>
      <div class="col mb-2">
        <div class="card" style="width: 18rem;" id="<%= dom_id subject %>">
          <div class="card-body">
            <%= render subject %>
            <p>
              <%= link_to t("show"), subject, class: "btn btn-primary" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if teacher_signed_in? %>
    <%= link_to t("common.new"), new_subject_path, class: "btn btn-secondary" %>
  <% end %>
  <% if student_signed_in? || teacher_signed_in? %>
    <%= link_to 'Export as CSV', export_csv_subjects_path(format: :csv), class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/subjects/new.html.erb
<div class="d-flex flex-column align-items-center">
  <p style="color: green"><%= notice %></p>

  <h1>New subject</h1>

  <%= render "form", subject: @subject %>
  <%= link_to "Back to subjects", subjects_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/subjects/show.html.erb
<div class="container mt-3">
  <p class="text-success"><%= notice %></p>

  <%= render @subject %>

  <div>
    <h4>Lessons:</h4>
    <ul>
      <% @subject.lessons.each do |related_subject| %>
        <li>
          <%= link_to related_subject.title, related_subject %>
        </li>
      <% end %>
    </ul>
  </div>


  <div class="btn-group mt-2" role="group" aria-label="Group actions">
    <% if teacher_signed_in?%>
      <%= link_to "Add Group", add_group_subject_path(subject_id: @subject.id), class: "btn btn-primary m-2 rounded" %>
      <%= link_to "Create Lesson", new_lesson_path(subject_id: @subject.id), class: "btn btn-primary m-2 rounded"%>
      <%= link_to "Edit this subject", edit_subject_path(@subject), class: "btn btn-primary m-2 rounded" %>
      <%= button_to "Destroy this subject", @subject, method: :delete, class: "btn btn-danger m-2 rounded" %>
    <% end %>
    <%= link_to "Back to subjects", subjects_path, class: "btn btn-secondary m-2 rounded" %>
  </div>
  
</div>