config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "application#welcome"
  get "chat_room/", to: "application#chat"
  scope "/:locale" do
    devise_for :students, path: "students", controllers: {sessions: "students/sessions",
                                                          registrations: "students/registrations",
                                                          passwords: "students/passwords"}
    devise_for :teachers, path: "teachers", controllers: {sessions: "teachers/sessions",
                                                          registrations: "teachers/registrations",
                                                          passwords: "students/passwords"}

    resources :subject_teachers
    resources :groups do
      member do
        get "add_students", action: "add_students_form"
        get "remove_students", action: "remove_students_form"
      end
      post "set_captain", on: :member
      post "add_students", on: :member
      post "remove_students", on: :member
    end
    resources :teachers
    resources :subjects do
      member do
        get "add_group", action: "add_group_form"
      end
      collection do
        get "export_csv"
      end
      post "add_group", on: :member
    end
    resources :lessons
    resources :tasks
    resources :students
    resources :marks
    resources :student_responses do
      post "evaluate", on: :member
    end
  end

  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["id", "email", "created_at", "updated_at"]
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :students, join_table: "groups_students"
  has_and_belongs_to_many :subjects
  has_many :group_students

  def captain
    captain_relation = group_students.find_by(captain: true)
    return unless captain_relation

    Student.find(captain_relation.student_id)
  end
end

app/models/group_student.rb
class GroupStudent < ApplicationRecord
  self.table_name = "groups_students"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :tasks
  enum lesson_type: {lecture: 0, seminar: 1, practical: 2}
  enum lesson_time: {
    "8:30" => 0,
    "10:10" => 1,
    "12:00" => 2,
    "13:40" => 3,
    "15:20" => 4,
    "17:00" => 5
  }

  scope :week_lessons, LessonsWeek
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  belongs_to :task

  validates :mark, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :recipient, polymorphic: true
end

app/models/student.rb
class Student < ApplicationRecord
  VALID_CURRENCIES = %w[USD EUR UAH].freeze
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :currency, presence: true, inclusion: { in: VALID_CURRENCIES }

  has_and_belongs_to_many :groups
  has_many :student_responses
  has_many :messages, as: :recipient
  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def currency_rates
    CurrencyRateService.call(self)
  end
end

app/models/student_response.rb
class StudentResponse < ApplicationRecord
  belongs_to :student
  belongs_to :task

  has_one_attached :file
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :teacher
  has_many :lessons

  scope :my_subjects, StudentSubjects

  def self.ransackable_attributes(auth_object = nil)
    %w[id title description hours created_at updated_at difficulty_level teacher_id lessons_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[groups lessons teacher]
  end

  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def self.to_csv
    attributes = %w{id title description hours created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << attributes.map { |attr| item.send(attr) }
      end
    end
  end

end

app/models/subject_teacher.rb
class SubjectTeacher < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :lesson
  has_many :student_responses, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  VALID_CURRENCIES = %w[USD EUR UAH].freeze
  validate :valid_email_domain

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :currency, presence: true, inclusion: { in: VALID_CURRENCIES }


  has_many :subjects
  has_many :messages, as: :recipient
  def first_initials
    "#{last_name} #{first_name.first}. #{middle_name.first}."
  end
  def self.recent(limit)
    order(created_at: :desc).limit(limit)
  end

  def currency_rates
    CurrencyRateService.call(self)
  end

  private

  def valid_email_domain
    allowed_domains = ["karazin.ua"]
    email_domain = email.split("@").last if email.present?
    return if allowed_domains.include?(email_domain)

    errors.add(:email, "wrong domen")
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EducationPlatformMpp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "content", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid text-light">
      <a class="navbar-brand text-light" href="#">OurNavBar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to t("home"), root_path, class: 'nav-link text-light' %>
          </li>
          <% if !teacher_signed_in? && !student_signed_in? %>
            <li class="nav-item">
              <%= link_to t("groups"), groups_path, class: 'nav-link text-light' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to  t("my_groups"), groups_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to  t("my_subjects"), subjects_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to t("schedule"), lessons_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to  t("chatroom"), '/chat_room', class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item mx-3">
            <%= link_to t("eng"), url_for(locale: "en"), class: 'nav-link text-light' %>
          </li>
          <li class="nav-item mx-3">
            <%= link_to t("ukr"), url_for(locale: "ua"), class: 'nav-link text-light' %>
          </li>
        </ul>
        <% if teacher_signed_in? || student_signed_in? %>
          <% exit_path = teacher_signed_in? ? destroy_teacher_session_path : destroy_student_session_path %>
          <% profile_path = teacher_signed_in? ? teacher_path(current_teacher) : student_path(current_student)  %>
          <ul class="navbar-nav">
            <li class="nav-item mx-3">
              <%= link_to t("profile"), profile_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item mx-3">
              <%= button_to t("logout"), exit_path, method: :delete, class: 'nav-link text-light' %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item mx-3">
              <%= link_to t("sign_in"), "#", style: "white-space: nowrap;", class: "nav-link text-light", "data-bs-toggle": "modal", "data-bs-target": "#sign_in_modal" %>
            </li>
            <li class="nav-item mx-3">
              <%= link_to t("sign_up"), "#", style: "white-space: nowrap;", class: "nav-link text-light", "data-bs-toggle": "modal", "data-bs-target": "#sign_up_modal" %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="modal fade" id="sign_up_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Sign in</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center">
            <%= link_to "Student sign up", new_student_registration_path, class: 'btn btn-secondary' %>
            <%= link_to "Teacher sign up", new_teacher_registration_path, class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="sign_in_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Sign in</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center">
            <%= link_to "Student sign up", new_student_session_path, class: 'btn btn-secondary' %>
            <%= link_to "Teacher sign in", new_teacher_session_path, class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
    <div class="flex justify-content-center container my-5 align-items-center rounded-3 border shadow-lg p-4" >
      <%= yield %>
    </div>
    
  </body>
</html>